/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package packagenou.projectegalan;

import at.favre.lib.crypto.bcrypt.BCrypt;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import models.Usuari;
import recursos.DataAcces;

/**
 *
 * @author Albert
 */
public class DialogLogIn extends java.awt.Dialog {
    
    private boolean isClosed = false;
    public interface LogInListener {
        void onLogInSuccessful();
    }
    private DataAcces da = new DataAcces();
    private LogInListener listener;
    /**
     * Creates new form DialogLogIn
     */
    private NouFramePrincipal nouFramePrincipal;
    public DialogLogIn(java.awt.Frame parent, boolean modal, LogInListener listener, NouFramePrincipal frame) {
        super(parent, modal);
        this.listener = listener; // Guardem el listener
        this.nouFramePrincipal = frame;
        initComponents();
        setResizable(false);
        
        
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtEmailLogin = new javax.swing.JTextField();
        txtPasswordLogin = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(719, 432));
        setMinimumSize(new java.awt.Dimension(719, 432));
        setPreferredSize(new java.awt.Dimension(719, 432));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setMaximumSize(new java.awt.Dimension(770, 477));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 477));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(770, 477));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEmailLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailLoginActionPerformed(evt);
            }
        });
        jPanel1.add(txtEmailLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 140, 40));
        jPanel1.add(txtPasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, 40));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 120, 50));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mail:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Contrassenya:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIA SESSIÓ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("I podràs fer pilates amb en Matrix");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel7.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\EnMatrixGros.png"));
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 300, 300));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hola guapo, has encalentit bé?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        jLabel8.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\MiddleLogoMesPetit.jpeg"));
        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 50, 50));

        jLabel6.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\fondo3 (1).jpg"));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
    // Indicar que el diàleg se ha cerrado
    setIsClosed(true);
    // Dispose para cerrar el JDialog
    dispose();
    }//GEN-LAST:event_closeDialog
public void setIsClosed(boolean isClosed) {
    this.isClosed = isClosed;
    firePropertyChange("closed", !isClosed, isClosed);  // Notificar el canvi d'estat
}
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    btnLogin.setEnabled(false); // Desactiva el botó per evitar més clics
    try {
        Usuari usuari = da.getUsuari(txtEmailLogin.getText());
        if (usuari != null) {
            char[] passwordToVerify = txtPasswordLogin.getPassword();
            String userPasswordHashInDatabase = usuari.getPasswordHash();
            var result = BCrypt.verifyer().verify(passwordToVerify, userPasswordHashInDatabase);
            
            if (result.verified) {
                JOptionPane.showMessageDialog(this, "Amaga sa testosterona " + usuari.getNom() + " que això pareix Melilla!");
                listener.onLogInSuccessful(); 
                nouFramePrincipal.playSound("src\\main\\java\\recursos\\audios\\Guardau.wav");
                nouFramePrincipal.setTrainer_id(da.getUserId(txtEmailLogin.getText()));
                setIsClosed(true);  // Indica que el diàleg s'ha tancat correctament
                dispose();  // Tancar el diàleg
            } else {
                JOptionPane.showMessageDialog(this, "ERROR Contrassenya: Que no pots passar Batuadeu!");
                nouFramePrincipal.playSound("src\\main\\java\\recursos\\audios\\Batuadeu.wav");
                btnLogin.setEnabled(true); // Reactiva el botó si hi ha error
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR Usuari: Qui ets tu Xac Norris? No hi ets per enlloc!");
            nouFramePrincipal.playSound("src\\main\\java\\recursos\\audios\\XacNorris.wav");
            btnLogin.setEnabled(true); // Reactiva el botó si hi ha error
        }
    } catch (Exception e) {
        btnLogin.setEnabled(true); // Reactiva el botó en cas d'error inesperat
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtEmailLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailLoginActionPerformed

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtEmailLogin;
    private javax.swing.JPasswordField txtPasswordLogin;
    // End of variables declaration//GEN-END:variables
}
