/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagenou.projectegalan;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.Intents;
import models.Usuari;
import recursos.DataAcces;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

public class FrameRevisarIntents extends javax.swing.JFrame {

    private EmbeddedMediaPlayerComponent mediaPlayer;
    private DataAcces dataAcces;
    private ArrayList<Intents> intentsPendents;
    private static final String VIDEO_FOLDER_PATH = "C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\videos\\";

       public FrameRevisarIntents() {
        initComponents();
        setResizable(false);
        dataAcces = new DataAcces();

        // Afegeix un `WindowListener` per inicialitzar `mediaPlayer` quan la finestra està visible
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                initializeMediaPlayer();
                loadPendingIntents();
                setupTableSelectionListener();
                selectAndPlayFirstIntent();
            }
        });
    }

           private void initializeMediaPlayer() {
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        pnlVideoPlayer.setLayout(new BorderLayout());
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);

        // Actualitza la interfície per assegurar que el component es mostra correctament
        revalidate();
        repaint();
    }
    private void loadPendingIntents() {
        intentsPendents = dataAcces.getPendingIntents();

        // Crear el model de taula amb 3 columnes: ID de l'intent, Nom de l'exercici, Nom de l'usuari
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID Intent", "Exercici", "Usuari","Data_Inici"}, 0);

        for (Intents intent : intentsPendents) {
            // Afegir les files amb la informació de l'intent, l'exercici i l'usuari
            tableModel.addRow(new Object[]{intent.getId(), intent.getExerciciNom(), intent.getUsuariNom(), intent.getInici()});
        }

        jTable1.setModel(tableModel);
    }

    private void setupTableSelectionListener() {
     jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int selectedRow = jTable1.getSelectedRow();
                Intents selectedIntent = intentsPendents.get(selectedRow);
                playVideo(selectedIntent.getVideo());
            }
        });
    }

    // Carregar automàticament el primer intent pendent en el reproductor de vídeo
    private void selectAndPlayFirstIntent() {
        if (!intentsPendents.isEmpty()) {
            jTable1.setRowSelectionInterval(0, 0);  // Selecciona la primera fila de la taula
            playVideo(intentsPendents.get(0).getVideo());  // Reprodueix el vídeo del primer intent
        }
    }

    private void playVideo(String videoFileName) {
        // Assegura't que el vídeo està detingut abans de carregar-ne un de nou
        if (mediaPlayer.mediaPlayer().status().isPlaying()) {
            mediaPlayer.mediaPlayer().controls().stop();
        }

        String videoPath = VIDEO_FOLDER_PATH + videoFileName;
        File videoFile = new File(videoPath);

        if (videoFile.exists()) {
            System.out.println("Reproduint vídeo: " + videoPath); // Depuració
            mediaPlayer.mediaPlayer().media().startPaused(videoFile.getAbsolutePath());
        } else {
            System.out.println("El fitxer de vídeo no existeix: " + videoPath); // Error de depuració
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFuncions = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        UsuarisPendents = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlVideoPlayer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPauseResumeVideoActionPerformed = new javax.swing.JButton();
        FondoFuncions = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(947, 512));
        setMinimumSize(new java.awt.Dimension(947, 512));
        setPreferredSize(new java.awt.Dimension(947, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFuncions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("<- SORTIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PanelFuncions.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        String text2 = "<html>Bernat: Mare meva Conco, al final<br>" +
        "m'hi hauré d'apuntar a nes gimnàs.</html>";
        jLabel4.setText(text2);
        PanelFuncions.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));

        jLabel8.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\MiddleLogoMesPetit.jpeg"));
        jLabel8.setText("jLabel8");
        PanelFuncions.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, 50, 50));

        jLabel2.setIcon(new ImageIcon("src/main/java/recursos/imatges/Bernat.png"));
        PanelFuncions.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 130, 120));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        String text = "<html>Conco Panareta: Ara ho veuràs<br>" +
        "amb lo fort que vaig m'aniràn<br>" +
        "darrera ses al·lotes, Bernat,<br>" +
        "duum una capsa de globos<br>" +
        "d'aquestes control sensitive.</html>";
        jLabel1.setText(text);
        PanelFuncions.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        UsuarisPendents.setBackground(new java.awt.Color(0, 0, 0));
        UsuarisPendents.setForeground(new java.awt.Color(255, 255, 255));
        UsuarisPendents.setText("Llista d'Usuaris amb Valoracions Pendents");
        UsuarisPendents.setToolTipText("");
        PanelFuncions.add(UsuarisPendents, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelFuncions.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 352, 300));

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - xxx.mp4"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());
        PanelFuncions.add(pnlVideoPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 480, 360));
        pnlVideoPlayer.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new ImageIcon("src/main/java/recursos/imatges/concofort.png"));
        PanelFuncions.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 210, 200));

        btnPauseResumeVideoActionPerformed.setText("Pausar/Reproduir");
        btnPauseResumeVideoActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformedActionPerformed(evt);
            }
        });
        PanelFuncions.add(btnPauseResumeVideoActionPerformed, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 146, 48));

        FondoFuncions.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\hobbiton (1).jpg"));
        PanelFuncions.add(FondoFuncions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 490));

        getContentPane().add(PanelFuncions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 490));

        jMenu2.setText("File");

        jMenu1.setText("Exit and Help");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu2.add(jMenu1);

        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseResumeVideoActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformedActionPerformed
      if (mediaPlayer.mediaPlayer().status().isPlaying()) {
        mediaPlayer.mediaPlayer().controls().pause();
    } else {
        mediaPlayer.mediaPlayer().controls().play();
}
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformedActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        String contingut = "El disseny de l'aplicació està basada amb \n" +
                            "la saga de parodies de Panareta.\n" + 
                            "Algunes de les imatges vistes estàn generades amb IA:\n" +
                            "He emprat: Pixlr, Ideogram, Stablediffusion\n" +
                            "He emprat audios de la aplicació oficial de Panareta Films:\n" + 
                            "https://play.google.com/store/apps/details?id=com.mitir.panereta.pfilms \n" +
                            "(Link només funcional a dispositius mòvils)";
        JOptionPane.showMessageDialog(this, contingut);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRevisarIntents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoFuncions;
    private javax.swing.JPanel PanelFuncions;
    private javax.swing.JLabel UsuarisPendents;
    private javax.swing.JButton btnPauseResumeVideoActionPerformed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}