/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagenou.projectegalan;

import java.awt.BorderLayout;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import models.Intents;
import models.Usuari;
import recursos.DataAcces;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

public class FrameRevisarIntents extends javax.swing.JFrame {

    private EmbeddedMediaPlayerComponent mediaPlayer;
    private DataAcces dataAcces;
    private ArrayList<Intents> intentsPendents;
    private static final String VIDEO_FOLDER_PATH = "C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\videos\\";

       public FrameRevisarIntents() {
        initComponents();
        setResizable(false);
        dataAcces = new DataAcces();

        // Afegeix un `WindowListener` per inicialitzar `mediaPlayer` quan la finestra està visible
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                initializeMediaPlayer();
                loadPendingIntents();
                setupTableSelectionListener();
                selectAndPlayFirstIntent();
            }
        });
    }

           private void initializeMediaPlayer() {
        mediaPlayer = new EmbeddedMediaPlayerComponent();
        pnlVideoPlayer.setLayout(new BorderLayout());
        pnlVideoPlayer.add(mediaPlayer, BorderLayout.CENTER);

        // Actualitza la interfície per assegurar que el component es mostra correctament
        revalidate();
        repaint();
    }
    private void loadPendingIntents() {
        intentsPendents = dataAcces.getPendingIntents();

        // Crear el model de taula amb 3 columnes: ID de l'intent, Nom de l'exercici, Nom de l'usuari
        DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID Intent", "Exercici", "Usuari","Data_Inici"}, 0);

        for (Intents intent : intentsPendents) {
            // Afegir les files amb la informació de l'intent, l'exercici i l'usuari
            tableModel.addRow(new Object[]{intent.getId(), intent.getExerciciNom(), intent.getUsuariNom(), intent.getInici()});
        }

        jTable1.setModel(tableModel);
    }

    private void setupTableSelectionListener() {
     jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() != -1) {
                int selectedRow = jTable1.getSelectedRow();
                Intents selectedIntent = intentsPendents.get(selectedRow);
                playVideo(selectedIntent.getVideo());
            }
        });
    }

    // Carregar automàticament el primer intent pendent en el reproductor de vídeo
    private void selectAndPlayFirstIntent() {
        if (!intentsPendents.isEmpty()) {
            jTable1.setRowSelectionInterval(0, 0);  // Selecciona la primera fila de la taula
            playVideo(intentsPendents.get(0).getVideo());  // Reprodueix el vídeo del primer intent
        }
    }

    private void playVideo(String videoFileName) {
        // Assegura't que el vídeo està detingut abans de carregar-ne un de nou
        if (mediaPlayer.mediaPlayer().status().isPlaying()) {
            mediaPlayer.mediaPlayer().controls().stop();
        }

        String videoPath = VIDEO_FOLDER_PATH + videoFileName;
        File videoFile = new File(videoPath);

        if (videoFile.exists()) {
            System.out.println("Reproduint vídeo: " + videoPath); // Depuració
            mediaPlayer.mediaPlayer().media().startPaused(videoFile.getAbsolutePath());
        } else {
            System.out.println("El fitxer de vídeo no existeix: " + videoPath); // Error de depuració
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelFuncions = new javax.swing.JPanel();
        UsuarisPendents = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlVideoPlayer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnPauseResumeVideoActionPerformed = new javax.swing.JButton();
        FondoFuncions = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1100, 490));
        setMinimumSize(new java.awt.Dimension(1100, 490));
        setPreferredSize(new java.awt.Dimension(1100, 490));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelFuncions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuarisPendents.setBackground(new java.awt.Color(255, 255, 255));
        UsuarisPendents.setText("Llista Usuaris pendents");
        UsuarisPendents.setToolTipText("");
        PanelFuncions.add(UsuarisPendents, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        PanelFuncions.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 352, 300));

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - xxx.mp4"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());
        PanelFuncions.add(pnlVideoPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 480, 360));
        pnlVideoPlayer.getAccessibleContext().setAccessibleName("");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\concofort.png")); // NOI18N
        PanelFuncions.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 220));

        btnPauseResumeVideoActionPerformed.setText("Pausar/Reproduir");
        btnPauseResumeVideoActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPauseResumeVideoActionPerformedActionPerformed(evt);
            }
        });
        PanelFuncions.add(btnPauseResumeVideoActionPerformed, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 146, 48));

        FondoFuncions.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\hobbiton (1).jpg")); // NOI18N
        FondoFuncions.setMaximumSize(new java.awt.Dimension(1100, 490));
        FondoFuncions.setMinimumSize(new java.awt.Dimension(1100, 490));
        FondoFuncions.setPreferredSize(new java.awt.Dimension(1100, 490));
        PanelFuncions.add(FondoFuncions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 490));

        getContentPane().add(PanelFuncions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 730));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPauseResumeVideoActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPauseResumeVideoActionPerformedActionPerformed
     if (mediaPlayer.mediaPlayer().status().isPlaying()) {
            mediaPlayer.mediaPlayer().controls().pause();
        } else {
            mediaPlayer.mediaPlayer().controls().play();
    }//GEN-LAST:event_btnPauseResumeVideoActionPerformedActionPerformed
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRevisarIntents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRevisarIntents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoFuncions;
    private javax.swing.JPanel PanelFuncions;
    private javax.swing.JLabel UsuarisPendents;
    private javax.swing.JButton btnPauseResumeVideoActionPerformed;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}
