/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package packagenou.projectegalan;

import java.awt.Font;

/**
 *
 * @author Albert
 */
public class JPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form JPanel2
     */
    public JPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTancar = new javax.swing.JButton();
        btnVideo = new javax.swing.JButton();
        btnRevisar = new javax.swing.JButton();
        Image2 = new javax.swing.JLabel();
        URL2 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        Fons1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        Labelgym = new javax.swing.JLabel();
        URL1 = new javax.swing.JLabel();
        Imatge1 = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();
        Fons2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(770, 477));
        setMinimumSize(new java.awt.Dimension(770, 477));
        setPreferredSize(new java.awt.Dimension(770, 477));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tomeu Quely:\"No Idoi si, has iniciat sessió\"");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 280, 50));

        btnTancar.setText("Tancar Sessió");
        btnTancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTancarActionPerformed(evt);
            }
        });
        add(btnTancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, -1));

        btnVideo.setText("Mirar Videos");
        btnVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVideoActionPerformed(evt);
            }
        });
        add(btnVideo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 160, 110, -1));

        btnRevisar.setText("Revisar Intents");
        btnRevisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisarActionPerformed(evt);
            }
        });
        add(btnRevisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 110, 110, -1));

        Image2.setText("jLabel2");
        add(Image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        URL2.setForeground(new java.awt.Color(255, 255, 255));
        URL2.setText("www.mallorcamitjagym.com");
        add(URL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 193, 47));

        Logo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\MiddleLogoPetit.jpeg")); // NOI18N
        add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, 100));

        Fons1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\fondo3 (1).jpg")); // NOI18N
        Fons1.setMaximumSize(new java.awt.Dimension(770, 477));
        Fons1.setMinimumSize(new java.awt.Dimension(770, 477));
        Fons1.setPreferredSize(new java.awt.Dimension(770, 477));
        add(Fons1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel1.setMaximumSize(new java.awt.Dimension(770, 477));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 477));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\MiddleLogo (1).jpeg")); // NOI18N
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 200));

        Labelgym.setForeground(new java.awt.Color(255, 255, 255));
        Labelgym.setText("Tomeu Quely, l'amo des gimnàs i bicampió de Mr.Olimpia");
        Labelgym.setPreferredSize(new java.awt.Dimension(1000, 1000));
        Labelgym.setFont(new Font("Arial", Font.BOLD, 15));
        jPanel1.add(Labelgym, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 620, 60));

        URL1.setForeground(new java.awt.Color(255, 255, 255));
        URL1.setText("www.mallorcamitjagym.com");
        jPanel1.add(URL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 193, 47));

        Imatge1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\TomeuQuelymesfort.png")); // NOI18N
        Imatge1.setText("jLabel2");
        jPanel1.add(Imatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        LogIn.setText("Comprate una moto que nos vamos para Lluc");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        jPanel1.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 360, 50));

        Fons2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\imatges\\fondo3 (1).jpg")); // NOI18N
        Fons2.setMaximumSize(new java.awt.Dimension(770, 477));
        Fons2.setMinimumSize(new java.awt.Dimension(770, 477));
        Fons2.setPreferredSize(new java.awt.Dimension(770, 477));
        jPanel1.add(Fons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRevisarActionPerformed

    private void btnVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVideoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVideoActionPerformed

    private void btnTancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTancarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTancarActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
    }//GEN-LAST:event_LogInActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fons1;
    private javax.swing.JLabel Fons2;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Imatge1;
    private javax.swing.JLabel Labelgym;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel URL1;
    private javax.swing.JLabel URL2;
    private javax.swing.JButton btnRevisar;
    private javax.swing.JButton btnTancar;
    private javax.swing.JButton btnVideo;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
