/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagenou.projectegalan;

import java.awt.CardLayout;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Albert
 */
public class NouFramePrincipal extends javax.swing.JFrame {

    private boolean isLoginDialogClosed = false;
    private int trainer_id;

    public void setTrainer_id(int trainer_id) {
        this.trainer_id = trainer_id;
    }

    static void mostraJPanel3() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form NouFramePrincipal
     */
    public NouFramePrincipal() {
        initComponents();
        setResizable(false);
        jPanel3.setVisible(false); // Inicialitza amb jPanel3 amagat
        LogIn.addActionListener(evt -> LogInActionPerformed(evt)); // Assignem l'acció del botó aquí
        pack();
    }

    // Aquest mètode s'invoca quan es prem el botó "Log In"                      
    private void obrirJDialogLogin() {
    if (!isLoginDialogClosed) { // Només obrir el diàleg si no ha estat tancat correctament
        DialogLogIn dialog = new DialogLogIn(this, true, this::mostrarJPanel3, this);

        // Listener per detectar quan el diàleg es tanca
        dialog.addPropertyChangeListener("closed", evt -> {
            if (evt.getNewValue().equals(true)) {
                isLoginDialogClosed = true;  // Marcar el diàleg com tancat
            }
        });

        dialog.setVisible(true);  // Mostrar el diàleg
    } else {
        System.out.println("S'ha tancat la finestra correctament");
    }
}

    // Aquest mètode canvia la visibilitat dels panells quan es fa login correctament


    private void onLogInSuccessful() {
        // Actualitza el control isLoginDialogClosed per evitar que es torni a mostrar el login
        isLoginDialogClosed = true;
        mostrarJPanel3(); // Canvia la visibilitat dels panells
    }
        private void mostrarJPanel3() {
        jPanel1.setVisible(false);
        jPanel3.setVisible(true);
        repaint();
        revalidate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo1 = new javax.swing.JLabel();
        Labelgym = new javax.swing.JLabel();
        URL1 = new javax.swing.JLabel();
        Imatge1 = new javax.swing.JLabel();
        LogIn = new javax.swing.JButton();
        Fons3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnIntents = new javax.swing.JButton();
        btnTancar = new javax.swing.JButton();
        btnUsuaris = new javax.swing.JButton();
        Image2 = new javax.swing.JLabel();
        URL2 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        Fons2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setMaximumSize(new java.awt.Dimension(770, 477));
        jPanel1.setMinimumSize(new java.awt.Dimension(770, 477));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\MiddleLogo (1).jpeg"));
        jPanel1.add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 200));

        Labelgym.setForeground(new java.awt.Color(255, 255, 255));
        Labelgym.setText("Tomeu Quely, l'amo des gimnàs i bicampió de Mr.Olimpia");
        Labelgym.setPreferredSize(new java.awt.Dimension(1000, 1000));
        Labelgym.setFont(new Font("Arial", Font.BOLD, 15));
        jPanel1.add(Labelgym, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 620, 60));

        URL1.setForeground(new java.awt.Color(255, 255, 255));
        URL1.setText("www.mallorcamitjagym.com");
        jPanel1.add(URL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 193, 47));

        Imatge1.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\TomeuQuelymesfort.png"));
        Imatge1.setText("jLabel2");
        jPanel1.add(Imatge1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 330));

        LogIn.setText("Comprate una moto que nos vamos para Lluc");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });
        jPanel1.add(LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 360, 50));

        Fons3.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\fondo3 (1).jpg"));
        Fons3.setMaximumSize(new java.awt.Dimension(770, 477));
        Fons3.setMinimumSize(new java.awt.Dimension(770, 477));
        Fons3.setPreferredSize(new java.awt.Dimension(770, 477));
        jPanel1.add(Fons3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel3.setMaximumSize(new java.awt.Dimension(770, 477));
        jPanel3.setMinimumSize(new java.awt.Dimension(770, 477));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 477));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tomeu Quely:\"No Idoi si, has iniciat sessió\"");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 280, 50));

        btnIntents.setText("Revisar Intents");
        btnIntents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntentsActionPerformed(evt);
            }
        });
        jPanel3.add(btnIntents, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 140, 40));

        btnTancar.setText("Tancar Sessió");
        btnTancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTancarActionPerformed(evt);
            }
        });
        jPanel3.add(btnTancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, 140, 40));

        btnUsuaris.setText("Usuaris");
        btnUsuaris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarisActionPerformed(evt);
            }
        });
        jPanel3.add(btnUsuaris, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 140, 40));

        Image2.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\GandalfRiguent.jpg"));
        Image2.setText("jLabel2");
        jPanel3.add(Image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 400, 330));

        URL2.setForeground(new java.awt.Color(255, 255, 255));
        URL2.setText("www.mallorcamitjagym.com");
        jPanel3.add(URL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 193, 47));

        Logo2.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\MiddleLogoPetit.jpeg"));
        jPanel3.add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 130, 100));

        Fons2.setIcon(new ImageIcon("src\\main\\java\\recursos\\imatges\\fondo3 (1).jpg"));
        Fons2.setMaximumSize(new java.awt.Dimension(770, 477));
        Fons2.setMinimumSize(new java.awt.Dimension(770, 477));
        Fons2.setPreferredSize(new java.awt.Dimension(770, 477));
        jPanel3.add(Fons2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTancarActionPerformed
    soundPlayed = false;
    isLoginDialogClosed = false;  // Tornar a marcar com no tancat el diàleg de login
    playSound("C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\audios\\AuDios.wav");
    // Amagar els panells actuals (si es necessari)
    jPanel1.setVisible(true);  // Amaga el panell principal (el de la sessió)
    jPanel3.setVisible(false);  // Amaga altres panells o panells de contingut

    // Mostrar el diàleg de login de nou // Torna a mostrar el diàleg de login

    // Opcionalment, netejar els camps de text del login per seguretat

    }//GEN-LAST:event_btnTancarActionPerformed

    private void btnUsuarisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarisActionPerformed
        FrameUsuaris frameUsuaris = new FrameUsuaris(this);
        frameUsuaris.setVisible(true);
    }//GEN-LAST:event_btnUsuarisActionPerformed

    public int getTrainer_id() {
        return trainer_id;
    }

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
    
    if (!soundPlayed) {
        playSound("src\\main\\java\\recursos\\audios\\moto.wav");
        soundPlayed = true;  // Marcar como reproducido
    }        obrirJDialogLogin();
    }//GEN-LAST:event_LogInActionPerformed
private boolean soundPlayed = false;

 public void playSound(String soundFilePath) {
    try {
        // Cargar el archivo de audio
        File soundFile = new File(soundFilePath);
        AudioInputStream audioIn = AudioSystem.getAudioInputStream(soundFile);
        Clip clip = AudioSystem.getClip();
        clip.open(audioIn);

        // Reproducir el sonido
        clip.start();
    } catch (UnsupportedAudioFileException | IOException | LineUnavailableException e) {
        System.err.println("Error al reproducir el sonido: " + e.getMessage());
    }
}
    private void btnIntentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntentsActionPerformed
        FrameRevisarIntents frameRevisarIntents = new FrameRevisarIntents();
        frameRevisarIntents.setVisible(true);
    }//GEN-LAST:event_btnIntentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new NouFramePrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fons2;
    private javax.swing.JLabel Fons3;
    private javax.swing.JLabel Image2;
    private javax.swing.JLabel Imatge1;
    private javax.swing.JLabel Labelgym;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel URL1;
    private javax.swing.JLabel URL2;
    private javax.swing.JButton btnIntents;
    private javax.swing.JButton btnTancar;
    private javax.swing.JButton btnUsuaris;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
