/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package packagenou.projectegalan;

import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JPanel;
import uk.co.caprica.vlcj.player.component.EmbeddedMediaPlayerComponent;

/**
 *
 * @author Albert
 */
public class VideoTestFrame extends JFrame {

    private EmbeddedMediaPlayerComponent mediaPlayer;
    private static final String VIDEO_FOLDER_PATH = "C:\\Users\\Albert\\Documents\\NetBeansProjects\\ActivitatsDVI\\Galan-Albert-DVI\\ProjecteGalan\\src\\main\\java\\recursos\\videos\\";
    private static final String VIDEO_FILE_NAME = "1280.mp4";  // Nom d'un vídeo de prova

    public VideoTestFrame() {
        // Configura el Frame bàsic
        setTitle("Test Reproductor de Vídeo VLCJ");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowOpened(java.awt.event.WindowEvent e) {
                // Només inicialitza el mediaPlayer quan la finestra està completament visible
                mediaPlayer = new EmbeddedMediaPlayerComponent();
                add(mediaPlayer, BorderLayout.CENTER);

                // Assegura't que el reproductor de vídeo està ben afegit a la finestra
                revalidate();
                repaint();

                // Carrega i reprodueix el vídeo de prova
                playVideo(VIDEO_FILE_NAME);
            }
        });
    }
    
private void playVideo(String videoFileName) {
        // Assegura't que el vídeo està detingut abans de carregar-ne un de nou
        if (mediaPlayer != null && mediaPlayer.mediaPlayer().status().isPlaying()) {
            mediaPlayer.mediaPlayer().controls().stop();
        }

        String videoPath = VIDEO_FOLDER_PATH + videoFileName;
        File videoFile = new File(videoPath);

        if (videoFile.exists()) {
            System.out.println("Reproduint vídeo: " + videoPath); // Depuració
            mediaPlayer.mediaPlayer().media().startPaused(videoFile.getAbsolutePath());
            mediaPlayer.mediaPlayer().controls().play(); // Inicia la reproducció
        } else {
            System.out.println("El fitxer de vídeo no existeix: " + videoPath); // Missatge d'error
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlVideoPlayer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVideoPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder("Video Player - xxx.mp4"));
        pnlVideoPlayer.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 517, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 343, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(77, 77, 77)
                    .addComponent(pnlVideoPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(77, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       java.awt.EventQueue.invokeLater(() -> {
            new VideoTestFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlVideoPlayer;
    // End of variables declaration//GEN-END:variables
}
